service: followme
frameworkVersion: "4"

provider:
  name: aws
  runtime: go1.x
  memorySize: 256
  environment:
    APP_NAME: ${self:service}-${sls:stage}

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  save_user:
    handler: bin/saveUser
    events:
      - http:
          path: users
          method: post
  save_location:
    handler: bin/saveLocation
    events:
      - http:
          path: locations
          method: post

plugins:
  - ./serverless-go-builder.js
  - serverless-offline
