service: followme
frameworkVersion: "4"

provider:
  name: aws
  runtime: go1.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  environment:
    APP_NAME: ${self:service}-${sls:stage}
    FIREBASE_DATABASE_URL: ${env:FIREBASE_DATABASE_URL}
    FIREBASE_SERVICE_KEY: serviceAccountKey.json

package:
  exclude:
    - ./**
  include:
    - ./bin/**
    - ./serviceAccountKey.json

functions:
  save_user:
    handler: bin/saveUser
    events:
      - http:
          path: users
          method: post
  save_location:
    handler: bin/saveLocation
    events:
      - http:
          path: locations
          method: post

plugins:
  - ./serverless-go-builder.js
  - serverless-offline
