service: followme
frameworkVersion: "4"

provider:
  name: aws
  runtime: go1.x
  memorySize: 256
  environment:
    APP_NAME: ${self:service}-${sls:stage}

functions:
  save_user:
    handler: bin/saveUser
    package:
      include:
        - ./bin/saveUser
    events:
      - http:
          path: users
          method: post
  save_location:
    handler: bin/saveLocation
    package:
      include:
        - ./bin/saveLocation
    events:
      - http:
          path: locations
          method: post
